### ISSUE TITLE
运行v2ctl通过，运行范例报错

### ISSUE THREAD

**Issue by kisaragychihaya** [ThunderingII/v2ray_python_client#2]
v2 配置文件`{
  "stats": {},
    "api": {
        "services": [
            "StatsService"
        ],
        "tag": "api"
    },
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "tag":"jerryrat",
    "port": 9665,
    "protocol": "vmess",
    "settings": {
      "clients": []
    },
        "streamSettings":{
      "network":"ws",
        "wsSettings": {
      "path": "/api"
      }
    }
  },
  "inboundDetour": [
        {
            "listen": "0.0.0.0",
            "port": 10085,
            "protocol": "dokodemo-door",
            "settings": {
                "address": "0.0.0.0"
            },
            "tag": "api"
        }
    ],
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        },
                {
                    "inboundTag": [
                        "api"
                    ],
                    "outboundTag": "api",
                    "type": "field"
        }
      ]
    }
  }
}
`
client.py
INBOUND_TAG = 'api'
SERVER_PORT = '10085'
SERVER_ADDRESS = 'myserverIP'
运行环境python3 debian8
错误信息
`Traceback (most recent call last):
  File "client.py", line 52, in <module>
    add_user(uid, email)
  File "client.py", line 40, in add_user
    value=vv
  File "/usr/lib/python3.4/site-packages/grpc/_channel.py", line 514, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/lib/python3.4/site-packages/grpc/_channel.py", line 448, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "OS Error"
        debug_error_string = "{"created":"@1534084884.478899961","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1095,"grpc_message":"OS Error","grpc_status":14}"`

**Comment by woyaoss2017** [comment]
`
def add_user(uuid, email, level=1, alter_id=32):
    INBOUND_TAG = 'proxy'
    SERVER_PORT = '8302'
    SERVER_ADDRESS = '127.0.0.1'
    channel = grpc.insecure_channel('%s:%s' % (SERVER_ADDRESS, SERVER_PORT))
    stub = command_pb2_grpc.HandlerServiceStub(channel)

    resp = stub.AlterInbound(
        command_pb2.AlterInboundRequest(
            tag=INBOUND_TAG,
            operation=typed_message_pb2.TypedMessage(
                type=command_pb2._ADDUSEROPERATION.full_name,
                value=command_pb2.AddUserOperation(
                    user=
                    user_pb2.User(
                        level=level,
                        email=email,
                        account=typed_message_pb2.TypedMessage(
                            type=account_pb2._ACCOUNT.full_name,
                            value=account_pb2.Account(
                                id=uuid,
                                alter_id=alter_id
                            ).SerializeToString()
                        )
                    )
                ).SerializeToString()
            )
        )
    )
    print(resp)
def remove_user(uuid, email, level=1, alter_id=32):
    INBOUND_TAG = 'proxy'
    SERVER_PORT = '8302'
    SERVER_ADDRESS = '127.0.0.1'
    channel = grpc.insecure_channel('%s:%s' % (SERVER_ADDRESS, SERVER_PORT))
    stub = command_pb2_grpc.HandlerServiceStub(channel)

    resp = stub.AlterInbound(
        command_pb2.AlterInboundRequest(
            tag=INBOUND_TAG,
            operation=typed_message_pb2.TypedMessage(
                type=command_pb2._REMOVEUSEROPERATION.full_name,
                value=command_pb2.RemoveUserOperation(
                    email=email          
                ).SerializeToString()
            )
        )
    )
    print(resp)`

增删用户都可以用了，获取状态部分咋写啊

**Comment by uimeet** [comment]
路由规则里面把  blocked 那个规则删掉。
