### ISSUE TITLE
protoc生成

### ISSUE THREAD

**Issue by Allen3** [ThunderingII/v2ray_python_client#5]
我的后台是node.js的，所以也要写一个你一样的 api client。
你是使用用`protoc`生成`.proto`文件所对应的`_pb`和`_grpc_pb`吗？

我使用`protoc`只能 生成`_pb`文件，`.proto`中所对应的那些service都没有生成到对应的`_grpc_pb`文件中，请问要使用什么其他工具吗？

**Comment by Allen3** [comment]
找到node的工具了，文档真的太少了。

**Comment by ThunderingII** [comment]
python里面需要安装
```shell
python -m pip install grpcio
python -m pip install grpcio-tools
```
这两个库去编译原来的文件，生成.proto对应的.py文件，你可能需要找一下有没有nodejs对应的gRPC的相关库

**Comment by Allen3** [comment]
嗯，node的库没有给文档，被我试出来了。
我能再问一下，那个`TypedMessage` proto 里面`type`字段应当填写的是`package`+这个message的名称吗？

**Comment by ThunderingII** [comment]
主要看怎么引用包的哦，应该每个.proto都会被编译成为一个类，所以调用的时候跟你的import有关

**Comment by Allen3** [comment]
API调用成功了，果然是包名+message名称，设计者设计的可扩展性非常好，便于区分不同的service以后提供API。
请问，增加的用户，好像没有修改`/etc/v2ray/config.json`文件，我要查询现有的用户，必须再使用API访问吗？还是如何操作呢？

**Comment by ThunderingII** [comment]
config 文件不会修改，这个我问了，只是增加在内存中，重启服务器失效。

**Comment by Allen3** [comment]
那得自己在文件中备份这个操作了。
感谢！
