### ISSUE TITLE
目前可以通过api添加SS inbound么？ 

### ISSUE THREAD

**Issue by rico93** [ThunderingII/v2ray_python_client#6]
大佬，方便指点一下吗，我不是很能看懂go

**Comment by ThunderingII** [comment]
可以添加inbound，但是 一个inbound 里面涉及到很多得object，比较麻烦

**Comment by rico93** [comment]
那目前的设定情况是，预先v2ray加载一个config.json 模板，然后往里面一个tag的inbound里面加user把。 那个多个object的这个，方便指条路么，比如应该看哪些文件的逻辑，我想试试哈哈哈

**Comment by ThunderingII** [comment]
我觉得有两个可行的路子：

1. 通过v2ray的api，但是这个好像是不保存到文件的，重启v2ray就失效了
2. 在服务器上面自己架设一个服务，直接修改config.json，然后通过shell 重载v2ray的配置文件

**Comment by rico93** [comment]
完全shell 重载的，我已经写完了。 但是遇到经常更新config就2333了。 目前想用你的这个api 的，但目前看起来就和前面说的vmess的写一下，可以建立一个config.json模板（不包括clinets），然后通过api增加user。 

但我目前想做到和重载config.json 一样，直接也能添加ss的用户，用v2来搞定ss。 你方便指点一下哪几个文件不

**Comment by ThunderingII** [comment]
[api](https://www.v2ray.com/chapter_02/api.html)

>一些对于入站出站代理进行修改的 API，可用的功能如下：
添加一个新的入站代理；
添加一个新的出站代理；
删除一个现有的入站代理；
删除一个现有的出站代理

从官方的看，貌似ss添加用户只能通过增加入站代理来实现，不能单独为某个代理增加用户，你可以检查下有没有修改入站代理的api，我之前记得可以的

然后我还有另外一个思路，如果你的传输协议为ws或者h2，可以使用nginx之类的做负载均衡，这样一台机器上布置两套v2ray，直接修改文件，应该可以做到不中断服务

**Comment by rico93** [comment]
谢啦，应该是config文件也是增加入站协议实现的。 谢啦我去具体看看，因为目前修改config，重载服务的方式，我直接能是实现，也想一样的条件改成api模式，虽然有些麻烦，但想基于你的代码，一点点加。谢啦

**Comment by rico93** [comment]
目前对我来说，比较难的是，怎么直接去找对应的修改入站的文件代码，你熟悉么？

**Comment by ThunderingII** [comment]
不熟悉，所以没有写啊，你写了可以push到我这个库，哈哈哈，比较繁杂，难度应该不大，就是复杂。

**Comment by rico93** [comment]
是的，就是复杂，得一点点看go的代码。不熟悉go啊，目前config的重载的，已经docker化了。 适配了一个前端 美滋滋

**Comment by rico93** [comment]
看到了具体的shadowsocks_test.go的代码，有信心了。

发自我的 iPhone

在 2018年12月4日，上午11:11，ThunderingII <notifications@github.com<mailto:notifications@github.com>> 写道：


不熟悉，所以没有写啊，你写了可以push到我这个库，哈哈哈，比较繁杂，难度应该不大，就是复杂。

**Comment by ThunderingII** [comment]
加油哦！老哥，你成功了可以帮忙push一下这个项目哦



发自我的小米手机
在 Rico <notifications@github.com>，2018年12月4日 12:12写道：

看到了具体的shadowsocks_test.go的代码，有信心了。

发自我的 iPhone

在 2018年12月4日，上午11:11，ThunderingII <notifications@github.com<mailto:notifications@github.com>> 写道：


不熟悉，所以没有写啊，你写了可以push到我这个库，哈哈哈，比较繁杂，难度应该不大，就是复杂。

**Comment by rico93** [comment]
好的啊

发自我的 iPhone

在 2018年12月4日，下午12:40，ThunderingII <notifications@github.com<mailto:notifications@github.com>> 写道：

加油哦！老哥，你成功了可以帮忙push一下这个项目哦



发自我的小米手机
在 Rico <notifications@github.com<mailto:notifications@github.com>>，2018年12月4日 12:12写道：

看到了具体的shadowsocks_test.go的代码，有信心了。

发自我的 iPhone

在 2018年12月4日，上午11:11，ThunderingII <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> 写道：


不熟悉，所以没有写啊，你写了可以push到我这个库，哈哈哈，比较繁杂，难度应该不大，就是复杂。

**Comment by rico93** [comment]
#7 增加了ss的设定。 目前简单测试能用了，通过error.log 基本是及时响应
